global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance', 'job', 'severity', 'teamowner', 'owner']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 3h
  receiver: teams-devops
  routes:
  - match:
      severity: warning
    continue: true
    receiver: teams-devops
  - match:
      severity: critical
    continue: true
    receiver: teams-devops
receivers:
- name: 'teams-devops'
  telegram_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    api_url: "https://api.telegram.org"
    bot_token: "5414687821:AAF28TJ3FmxnRRCG4NEK_DqyHbE2RZ5AMbE"
    chat_id: -730234381
    message: '{{ template "telegram.default.message" . }}'
    parse_mode: HTML
templates:
- '/etc/alertmanager/template/default.tmpl'
