version: '3.3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: reverseproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/staraip.crt:/root/ssl/staraip.crt
      - ./ssl/staraip.key:/root/ssl/staraip.key
    restart: unless-stopped     # or "always"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    networks:
      - nginx_hub
networks:
  nginx_hub:
    external: true
