global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'Monitoring Hosts/Containers AIP'

###Mounted directory of alert rule on container Prometheus
rule_files:
  - "/etc/prometheus/alert-rules/alert.rules.yml"

alerting:
  alertmanagers:
  - scheme: http
    timeout: 30s
    static_configs:
      - targets: ["10.96.11.47:9093"]

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ["10.96.11.47:9090"]
        labels:
          instance: prometheus
          host: prometheus
          ip: 10.96.11.47
          site: CRM
          application: prometheus-monitor-crm
          infrastructure: monitor-crm
          company: AIP
          teamowner: DevOps
          environment: Prod
          tag: infrastructure

  - job_name: "alertmanager"
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ["10.96.11.47:9093"]
        labels:
          instance: alertmanager
          host: alertmanager
          ip: 10.96.11.47
          site: CRM
          application: alertmanager-monitor-crm
          infrastructure: monitor-crm
          company: AIP
          teamowner: DevOps
          environment: Prod
          tag: infrastructure

  - job_name: "node_exporter"
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ["10.96.11.47:9100"]
        labels:
          instance: monitor-crm
          host: monitor-crm
          ip: 10.96.11.47
          site: CRM
          application: node-exporter-monitor-crm
          infrastructure: monitor-crm
          company: AIP
          teamowner: DevOps
          environment: Prod
          tag: infrastructure
      - targets: ["10.96.11.178:9100"]
        labels:
          instance: prod-docker-crm
          host: prod-docker-crm
          ip: 10.96.11.178
          site: CRM
          application: node-exporter-prod-crm
          infrastructure: prod-crm
          company: AIP
          teamowner: DevOps
          environment: Prod
          tag: infrastructure

  - job_name: "cadvisor"
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ["10.96.11.47:8080"]
        labels:
          instance: monitor-crm
          host: monitor-crm
          ip: 10.96.11.47
          site: CRM
          application: cadvisor-monitor-crm
          infrastructure: monitor-crm
          company: AIP
          teamowner: DevOps
          environment: Prod
          tag: infrastructure
      - targets: ["10.96.11.178:8080"]
        labels:
          instance: prod-docker-crm
          host: prod-docker-crm
          ip: 10.96.11.178
          site: CRM
          application: cadvisor-prod-crm
          infrastructure: prod-crm
          company: AIP
          teamowner: DevOps
          environment: Prod
          tag: infrastructure

#  - job_name: "kafka"
#    scrape_interval: 15s
#    scrape_timeout: 15s
#    static_configs:
#      - targets: ["10.96.17.142:1309"]
#        labels:
#          instance: kafka-amilo-testing
#          host: kafka-amilo-testing
#          ip: 10.96.17.142
#          site: Amilo
#          application: kafka-amilo-testing
#          infrastructure: kafka-amilo-testing
#          company: AIP
#          teamowner: DevOps
#          environment: Test
#          tag: infrastructure
#
#  - job_name: 'blackbox_exporter'
#    scrape_interval: 30s
#    scrape_timeout: 30s
#    metrics_path: /probe
#    params:
#      module: ['tcp_connect']
#    static_configs:
#    - targets: ['ip:port']
#      labels:
#        instance: name
#        host: name
#        ip: ip
#        site: AIP
#        application: application
#        service: service
#        port: port
#        infrastructure: infrastructure
#        company: AIP
#        teamowner: DevOps
#        environment: Prod
#        tag: service
#
